name: library_app
description: "Aplikasi Perpustakaan Digital dengan Flutter GetX & Firebase."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- PLUGIN WAJIB ---
  get: ^4.6.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_fonts: ^6.2.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  mobile_scanner: ^5.1.1
  introduction_screen: ^3.1.14
  
  # âœ… Plugin Rating (Sudah Masuk)
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon.png"
  android_12: 
    image: "assets/icon.png"
    color: "#FFFFFF"
  fullscreen: true